=== Vyacheslav-Lapin/testauto/src/main/resources/notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.tc.com/notes"
              xmlns:tns="http://www.epam.tc.com/notes"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
            http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
        elementFormDefault="qualified">

    <element name="notes">
        <complexType>
            <sequence>
                <element name="note" type="tns:Note" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Note">
        <sequence>
            <element name="to" type="string"/>
            <element name="сustomer-location" type="string" fixed="UK"/>
            <element name="from" type="string"/>
            <element name="heading" type="string"/>
            <element name="body" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

</schema>

=== Vyacheslav-Lapin/testauto/src/main/resources/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<notes xmlns="http://www.epam.tc.com/notes"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.epam.tc.com/notes ./notes.xsd">

    <note id="1">
        <to>Vasya</to>
        <сustomer-location>UK</сustomer-location>
        <from>Sveta</from>
        <heading>Napominanie</heading>
        <body>Pozvoni</body>
    </note>

    <note id="2">
        <to>Вася</to>
        <сustomer-location/>
        <from>Света</from>
        <heading>Напоминание</heading>
        <body>Позвони мне завтра!</body>
    </note>

</notes>
